(if window-system (set-face-attribute 'default nil :font "Inconsolata-18"))
;; font
;; (if window-system (set-face-attribute 'default nil :font "Liberation Mono-14"))
;; (if window-system (set-face-attribute 'default nil :font "Liberation Mono-18"))
;; (if window-system (set-face-attribute 'default nil :font "Droid Sans Mono-14"))
;; (if window-system (set-face-attribute 'default nil :font "Droid Sans Mono-16"))
;; (if window-system (set-face-attribute 'default nil :font "Droid Sans Mono-18"))
;; (if window-system (set-face-attribute 'default nil :font "Droid Sans Mono-20"))
;; (if window-system (set-face-attribute 'default nil :font "Droid Sans Mono-22"))
;; (if window-system (set-face-attribute 'default nil :font "Monaco-16"))
;; (if window-system (set-face-attribute 'default nil :font "Monaco-14"))
;; (if window-system (set-face-attribute 'default nil :font "Monaco-18"))
;; (if window-system (set-face-attribute 'default nil :font "Monaco-20"))
;; (if window-system (set-face-attribute 'default nil :font "Consolas-24"))
;; (if window-system (set-face-attribute 'default nil :font "Consolas-20"))
;; (if window-system (set-face-attribute 'default nil :font "Consolas-22"))
;; (if window-system (set-face-attribute 'default nil :font "Consolas-14"))
;; (if window-system (set-face-attribute 'default nil :font "Terminus-14"))
;; (if window-system (set-face-attribute 'default nil :font "Terminus-18"))
;; (if window-system (set-face-attribute 'default nil :font "Source Code Pro-12"))
;; (if window-system (set-face-attribute 'default nil :font "Source Code Pro-14"))
;; (if window-system (set-face-attribute 'default nil :font "Source Code Pro-16"))
;; (if window-system (set-face-attribute 'default nil :font "Source Code Pro-18"))
;; (if window-system (set-face-attribute 'default nil :font "Source Code Pro-20"))
